### ISSUE TITLE
Goldstone server RPM packaging part deux

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#234]
Would like to have a solution similar to what @slashk has done with goldstone-agent.  Should:

- use versioning format consistent with agent 
- integrate with CircleCI (talk to @heidecke)
- build the opensource version as RPM (no compliance submodule installed)
- build the enterprise version as RPM (compliance submodule installed)

Decide where to store the RPMS.  Enterprise should go to bintray (secured).  OpenSource could go to one or more of a) CircleCI artifacts, b) github releases page, c) bintray (unsecured)

**Comment by slashk** [comment]
Current status ([circleci build 213](https://circleci.com/gh/Solinea/goldstone-server/213)):

* ported `semver.sh` for consistent versioning
* `circle.yml` updated to build gs and gse packages. packages currently at circleci artifacts.

Currently status/bugs:

* versioning of packages differs between local and circleci ( **local**: `goldstone-server-0.7.2-SNAPSHOT.498.gb8a2e5f.rpm.el7.x86_64.rpm`, **circleci**: `goldstone-server-new-SNAPSHOT.dashboard.162.gc4be4a9.rpm.el7.x86_64.rpm`). i think that it is getting the `-new` instead of tag from pulling as a detached head. @heidecke thoughts ?
* need to do real integration tests on resulting rpm -- they pass smoke tests in containers.
