### ISSUE TITLE
first pass elasticsearch tuning

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#432]
Allocation of memory and file descriptors inside the docker container.  It should be aware of the available memory on the underlying host, and allocate 25% of host memory to ES container, and 50% of ES container memory to ES.  

Also set file descriptors for ES to 64K.

**Comment by jxstanford** [comment]
@heidecke @vichargrave for 1.1, please keep the ES version at 1.7.1 unless there is a solid reason to change.  I'm assuming for 2.0, we can shoot for ES 5.  I would like to open up the possibility of using the graph API in there for some future features.

**Comment by vichargrave** [comment]
After talking with Luke, I think setting the container size to 25% of the RAM on a given system is not straightforward.  It seems that the container memory specification is a soft limit.  However I believe setting the ES_HEAP_SIZE for Elasticsearch to 1Gb is a reasonable value for now.  Ultimately I want to figure out how Elasticsearch clusters are built using Elasticsearch containers so that we can allocate more heap in larger Goldstone deployments.

**Comment by heidecke** [comment]
Here's some examples on how to use elasticsearch in production in containers.

**Generic Elasticsearch Example**
https://github.com/kubernetes/kubernetes/tree/release-1.2/examples/elasticsearch

**Production Elasticsearch Role Separation**
https://github.com/kubernetes/kubernetes/blob/release-1.2/examples/elasticsearch/production_cluster/README.md

**Kubernetes Discovery Plugin for Elasticsearch**
https://github.com/fabric8io/elasticsearch-cloud-kubernetes

**Fluentd Elasticsearch Example w/ Dockerfiles**
https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch
Example fluentd shipper that runs on each node: https://github.com/kubernetes/kubernetes/blob/release-1.2/cluster/saltbase/salt/fluentd-es/fluentd-es.yaml

**Comment by vichargrave** [comment]
I'd like to remove the part of this issue involving file descriptors.  Since we map the gssearch data volume to an external path, setting the maximum number of file descriptors is something that has to be done on the system on which goldstone-server is deployed.  I think this is out of scope for our deployment packages.  However, if it something we can control upon installation, then I suggest opening a separate issue for setting the max file descriptors.

**Comment by vichargrave** [comment]
Closed after pull request 509 merged (https://github.com/Solinea/goldstone-server/pull/509)
