### ISSUE TITLE
mismatch in dropdown vs saved search: API

### ISSUE THREAD

**Issue by Alicia-Solinea** [Solinea/goldstone-server#470]
On the Reports -> API Call Viewer, the predefined searches dropdown displays 2 options (none, slow api calls). But if you hit  configure, and go to the Saved Search: API Browser page, there are 3 options listed (api call query, service status, slow api calls).  Either the Saved Search page or predefined searches dropdown needs to be updated to reflect the same options. Screenshot attached.
![apicallsearch](https://cloud.githubusercontent.com/assets/17206771/14497981/633f8fa4-015e-11e6-9d2f-1dc634dfb38d.png)

**Comment by lexjacobs** [comment]
added to UI Design epic. Will be addressed as part of site usability redesign process.

**Comment by jxstanford** [comment]
@vichargrave can you double check that the "service status" search has hidden = true?  I believe client is using that to filter out things to not display.

**Comment by vichargrave** [comment]
The hidden field in this case is set to 'false'.

**Comment by lexjacobs** [comment]
It appears that we have a filter in the client for a few queries:

```
// do not render these searches in any of the dropdown lists
    bannedSearchList: {
        'service status': true,
        'api call query': true,
        'event query': true,
        'log query': true
    },
```

**Comment by vichargrave** [comment]
So should I set the hidden field to 'true'?

**Comment by jxstanford** [comment]
@vichargrave yes.  @lexjacobs if you want to filter on hidden=false, that was what it was created for.

**Comment by lexjacobs** [comment]
please pass the ticket to me before you merge this for client modifications.

**Comment by vichargrave** [comment]
Over to you  alex.

**Comment by lexjacobs** [comment]
@jxstanford side affect of setting search to hidden=false rediscovered:

`core/saved_search/?page_size=25&page=1&ordering=name&index_prefix=api_stats-*`
originally returned 3 results which showed up under "Saved Searches: API Browser
" viewable at http://localhost:8000/#reports/apibrowser/search  and pasted in the first message in this issue thread. they were: api call query/ service status/ slow api calls.

please note that the `hidden` key does not show up in the api result returned to the client.
so this is not a viable key for the client to use in order to hide a saved search.

after setting the saved search to `hidden: true`, the result is not returned when the api call is made to: /core/saved_search/.

when viewing the list of saved searches, including the systems searches that cannot be deleted, the hidden saved search is now invisible. as seen at `http://localhost:8000/#reports/apibrowser/search`

so as long as hidden searches being completely obscured to the client is okay, then we can continue with this usage of "hidden" and it should also be used for:
- api call query
- event query
- log query

please advise.

**Comment by lexjacobs** [comment]
![screen shot 2016-04-15 at 6 14 48 pm](https://cloud.githubusercontent.com/assets/5633015/14578176/006475d2-0336-11e6-8f7a-24f0fe8b4e4c.png)
![screen shot 2016-04-15 at 6 14 40 pm](https://cloud.githubusercontent.com/assets/5633015/14578177/0067d1d2-0336-11e6-90b1-67cdfcbdc041.png)

![screen shot 2016-04-15 at 6 15 37 pm](https://cloud.githubusercontent.com/assets/5633015/14578180/153d332c-0336-11e6-98e3-575c26c111e9.png)

**Comment by jxstanford** [comment]
After reviewing with @lexjacobs my understanding of the role of the hidden field has been clarified.  Hidden searches are filtered and not sent via the API to the client.  We probably need another boolean field on a SavedSearch like 'viewer_enabled' so the client can choose to only present those Searches in the Log/Event/API call viewers and associated editors.

**Comment by vichargrave** [comment]
Added the viewer_enabled flag.  Over to Alex for the UI.

**Comment by lexjacobs** [comment]
@vichargrave client modifications pushed. Please note that viewer_enabled is currently returning false for all searches. 

I have enabled client sensitivity to this key for all of the predefined search drop downs on pages such as:
http://localhost:8000/#reports/logbrowser

as well as on the saved search manager pages such as:
http://localhost:8000/#reports/logbrowser/search

Please verify that you get the same results and that when you load these pages there are currently 0 results returning.

**Comment by vichargrave** [comment]
Closed after pull request https://github.com/Solinea/goldstone-server/pull/495 closed
